name : First Workflow
on : workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - names: Prit greeting
        run: echo "hello world!"
      - name: Print goodbye
        run: echo "Done - bye!"
